/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sign in with email and password
     * @description Checks the password against the bcrypt hash from the users file and sets the session cookie. A removed account and a wrong password get the same 401, so the response never says which emails exist.
     */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sign out
     * @description Clears the session cookie. Safe to repeat; a caller with no session also gets 204.
     */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The signed-in user, their outlet and the brand */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Whether the server can reach PostgreSQL
     * @description For the operator and the Docker health check (HLD section 7).
     */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/outlets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List outlets with their managers and review counts
     * @description The brand admin gets every outlet; an outlet manager gets only their own. Ordered by name. Returned whole (tens of rows), no cursor.
     */
    get: operations["listOutlets"];
    put?: never;
    /**
     * Add an outlet (brand admin)
     * @description Names are unique ignoring capitals and are stored trimmed. A name that already exists is 409 outlet_name_taken, which also answers a repeated request; its details hold one item, field name, whose reason is the existing outlet's name as stored (for example "Koramangala" when "koramangala" was sent), so the UI can show it.
     */
    post: operations["createOutlet"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/imports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import reviews from a CSV file (brand admin)
     * @description Reads the columns outlet, source, date, rating, text and reviewer_name; all six are required in every row. Valid new rows are stored, rows already imported (same outlet, source, date, reviewer and text) are counted as duplicates, and each rejected row is returned with its row number and reason; all in one transaction. A whole-file problem (not a CSV, a missing column) imports nothing and is 400 csv_invalid. When the import commits, tagging starts on its own (Q-022). Runs through the connector interface; CSV is the only connector (REQ-004, REQ-005).
     */
    post: operations["createImport"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/themes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The configured theme list
     * @description One list for the installation, set in configuration by a developer (Q-012); initially food, wait time, staff, cleanliness and price. Used by the review filters and the heatmap columns.
     */
    get: operations["listThemes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reviews": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search and filter reviews, newest first
     * @description Text search over review text and reviewer name, plus filters for outlet, theme, sentiment, urgent, reply status and date range (Q-020). Sorted by review_date then id, newest first. An outlet manager sees only their outlet; filter[outlet_id] naming another outlet is 404. Untagged reviews match no theme, sentiment or urgent filter. total counts every match, not just this page.
     */
    get: operations["listReviews"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reviews/{review_id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 1497 */
        review_id: components["parameters"]["ReviewId"];
      };
      cookie?: never;
    };
    /**
     * One review with its tags, reply and the outlet's managers
     * @description Never calls the model. The brand admin reads any review, including its draft (admin view); an outlet manager reads only their outlet's reviews. can_reply says whether this caller may draft, edit and mark it replied.
     */
    get: operations["getReview"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reviews/{review_id}/draft": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 1497 */
        review_id: components["parameters"]["ReviewId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get the stored draft, or draft one with the model (outlet manager)
     * @description Called when the manager opens a review (Q-007). If a reply exists it is returned with no model call. Otherwise the server claims the reply and asks the gateway for a draft with the current reply prompt version, in the review's language (Q-009). If another request is drafting the same review, the answer is 202 with status drafting and Retry-After; call again. When drafting is unavailable (budget used up, provider credit, provider down, or 45 seconds passed) the claim is released and the manager can write the reply by hand with PUT reply.
     */
    post: operations["createReplyDraft"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reviews/{review_id}/reply": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 1497 */
        review_id: components["parameters"]["ReviewId"];
      };
      cookie?: never;
    };
    get?: never;
    /**
     * Save the reply text (outlet manager)
     * @description Saves an edit to the draft, or creates a hand-written reply when there is none (based_on_updated_at null), for example while drafting is unavailable. Refused with 409 reply_changed when the reply changed since the client read it, 409 draft_in_progress while the model is drafting, and 409 already_replied once the reply is approved: an approved text never changes.
     */
    put: operations["saveReply"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reviews/{review_id}/replied": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 1497 */
        review_id: components["parameters"]["ReviewId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Approve the reply text and mark the review replied (outlet manager)
     * @description Approval and marking replied are one action (Q-008). Stores reply_text as the final text with the manager and the time, only if the reply is unchanged since the client read it. Only the manager of the review's outlet may do this; the brand admin gets 403 (Q-002). A review already replied is returned unchanged with 200, so a repeat is safe.
     */
    post: operations["markReplied"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard/trends": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Weekly rating, sentiment and reply counts per outlet, last 12 complete weeks
     * @description One row per outlet the caller may see, one entry per Monday to Sunday week in the brand timezone, oldest first, ending with the latest complete week. Sentiment counts cover tagged reviews only; untagged is the rest.
     */
    get: operations["getTrends"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard/heatmap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Negative reviews by outlet and theme, last 4 complete weeks
     * @description One row per outlet the caller may see and one count per configured theme. A review tagged with two themes counts once under each (Q-021). The cell measure is the number of negative reviews (screen S-03).
     */
    get: operations["getHeatmap"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard/movers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Biggest movers, latest complete week against the week before
     * @description Outlet and theme pairs ranked by the size of the change in the number of negative reviews tagged with that theme (Q-004, Q-005); ties put a rise before a fall, then outlet name, then theme. Pairs with no change are left out. untagged_count is the number of reviews dated in the two weeks still untagged, so the screen can warn that movers may be incomplete.
     */
    get: operations["getMovers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tagging/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Untagged count, worker state and budget state
     * @description Read by the top bar and the overview banners (budget stop, tagging paused). For an outlet manager, untagged_count covers their outlet only; the worker and budget state are the installation's.
     */
    get: operations["getTaggingStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/digests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate the weekly digest and email it to the brand admin
     * @description Generated on demand only (Q-005) for the latest complete Monday to Sunday week against the week before. The digest is recorded as sending before SMTP is called, then sent; one email goes to the brand admin through MailHog (Q-006). A repeat with the same Idempotency-Key returns the recorded digest and never sends again: 201 if it was sent, 202 if it is still marked sending, 502 if it failed. To try again after a failure, use a new key.
     */
    post: operations["createDigest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @example {
     *       "error": {
     *         "code": "validation_failed",
     *         "message": "reply_text must not be blank",
     *         "details": [
     *           {
     *             "field": "reply_text",
     *             "reason": "blank"
     *           }
     *         ],
     *         "request_id": "req_01J9Z6"
     *       }
     *     }
     */
    Error: {
      error: {
        code: string;
        message: string;
        details?: {
          field: string;
          reason: string;
        }[];
        request_id: string;
      };
    };
    /**
     * @example {
     *       "next_cursor": "eyJkIjoiMjAyNi0xMC0wMyIsImlkIjoxNDk3fQ",
     *       "has_more": true
     *     }
     */
    Page: {
      next_cursor: string | null;
      has_more: boolean;
    };
    /**
     * @example {
     *       "status": "ok"
     *     }
     */
    Health: {
      /** @enum {string} */
      status: "ok";
    };
    /**
     * @example {
     *       "email": "arjun.mehta@example.in",
     *       "password": "correct-horse-battery"
     *     }
     */
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    /**
     * @example {
     *       "id": 2,
     *       "name": "Arjun Mehta"
     *     }
     */
    UserRef: {
      /** Format: int64 */
      id: number;
      name: string;
    };
    /**
     * @example {
     *       "id": 1,
     *       "name": "Koramangala"
     *     }
     */
    OutletRef: {
      /** Format: int64 */
      id: number;
      name: string;
    };
    /**
     * @example {
     *       "id": 2,
     *       "email": "arjun.mehta@example.in",
     *       "name": "Arjun Mehta",
     *       "role": "outlet_manager",
     *       "outlet": {
     *         "id": 1,
     *         "name": "Koramangala"
     *       },
     *       "brand": {
     *         "name": "Neem Tree Kitchens",
     *         "timezone": "Asia/Kolkata"
     *       }
     *     }
     */
    Me: {
      /** Format: int64 */
      id: number;
      /** Format: email */
      email: string;
      name: string;
      /** @enum {string} */
      role: "brand_admin" | "outlet_manager";
      /** @description The manager's one outlet; null for the brand admin. */
      outlet: components["schemas"]["OutletRef"] | null;
      /** @description From configuration; one brand per installation (Q-001). */
      brand: {
        name: string;
        /** @description IANA zone that bounds the Monday to Sunday weeks. */
        timezone: string;
      };
    };
    /**
     * @example {
     *       "id": 6,
     *       "name": "Electronic City",
     *       "managers": [],
     *       "review_count": 0,
     *       "untagged_count": 0,
     *       "created_at": "2026-10-06T05:00:00Z"
     *     }
     */
    OutletSummary: {
      /** Format: int64 */
      id: number;
      name: string;
      /** @description Active outlet managers; empty means nobody can reply to this outlet's reviews yet. */
      managers: components["schemas"]["UserRef"][];
      review_count: number;
      untagged_count: number;
      /** Format: date-time */
      created_at: string;
    };
    /**
     * @example {
     *       "name": "Electronic City"
     *     }
     */
    OutletCreate: {
      /** @description Trimmed before it is stored. */
      name: string;
    };
    /**
     * @example {
     *       "file": "outlet,source,date,rating,text,reviewer_name"
     *     }
     */
    ImportUpload: {
      /** @description UTF-8 CSV, at most 5 MB, with a header row naming outlet, source, date, rating, text and reviewer_name. date is YYYY-MM-DD; rating is a whole number 1 to 5; text up to 5,000 characters; outlet, source and reviewer_name up to 200. */
      file: string;
    };
    /**
     * @example {
     *       "row_number": 118,
     *       "reason": "Rating is \"4.5\"; ratings must be a whole number from 1 to 5."
     *     }
     */
    ImportRejection: {
      /** @description Row in the file as a spreadsheet numbers it; the header is row 1. */
      row_number: number;
      reason: string;
    };
    /**
     * @example {
     *       "id": 12,
     *       "file_name": "reviews-sept.csv",
     *       "imported_count": 479,
     *       "duplicate_count": 14,
     *       "rejected_count": 3,
     *       "rejections": [
     *         {
     *           "row_number": 37,
     *           "reason": "Unknown outlet \"Koramangla\". Check the spelling against your outlet names."
     *         },
     *         {
     *           "row_number": 118,
     *           "reason": "Rating is \"4.5\"; ratings must be a whole number from 1 to 5."
     *         },
     *         {
     *           "row_number": 240,
     *           "reason": "Date is empty."
     *         }
     *       ],
     *       "created_at": "2026-10-06T05:10:00Z"
     *     }
     */
    ImportResult: {
      /** Format: int64 */
      id: number;
      file_name: string;
      imported_count: number;
      /** @description Rows already imported, counted and not stored. */
      duplicate_count: number;
      rejected_count: number;
      /** @description Every rejected row, in row order. */
      rejections: components["schemas"]["ImportRejection"][];
      /** Format: date-time */
      created_at: string;
    };
    /**
     * @example {
     *       "code": "wait_time",
     *       "label": "Wait time"
     *     }
     */
    Theme: {
      code: string;
      label: string;
    };
    /**
     * @example negative
     * @enum {string}
     */
    Sentiment: "positive" | "neutral" | "negative";
    /**
     * @example {
     *       "themes": [
     *         "wait_time",
     *         "staff"
     *       ],
     *       "sentiment": "negative",
     *       "is_urgent": false,
     *       "urgent_reasons": [],
     *       "prompt_version": 2
     *     }
     */
    Tags: {
      /** @description Zero, one or several theme codes (Q-021). */
      themes: string[];
      sentiment: components["schemas"]["Sentiment"];
      /** @description Food safety, harassment or a legal threat (REQ-010); true exactly when urgent_reasons is not empty. The one exception: rows tagged before the fallback migration 00005, if it is ever used (data model v2 section 8), can be urgent with no reason, and the UI then shows Urgent with no kind. */
      is_urgent: boolean;
      /** @description Why the review is urgent, shown beside it on screens S-02, S-04, S-05 and S-08 and in the digest; the screens show each reason. Several allowed, none repeated, returned in the fixed order food_safety, harassment, legal_threat; empty when not urgent (data model v2). */
      urgent_reasons: ("food_safety" | "harassment" | "legal_threat")[];
      /** @description The tagging prompt version that produced these tags (Q-011). */
      prompt_version: number;
    };
    /**
     * @example {
     *       "id": 1488,
     *       "outlet": {
     *         "id": 5,
     *         "name": "Jayanagar"
     *       },
     *       "source": "Google",
     *       "review_date": "2026-10-02",
     *       "rating": 1,
     *       "review_text": "खाने में कीड़ा मिला और रात को मेरे बेटे का पेट खराब हो गया।",
     *       "reviewer_name": "Sunita Verma",
     *       "tags": {
     *         "themes": [
     *           "food",
     *           "cleanliness"
     *         ],
     *         "sentiment": "negative",
     *         "is_urgent": true,
     *         "urgent_reasons": [
     *           "food_safety"
     *         ],
     *         "prompt_version": 2
     *       },
     *       "reply_status": "none"
     *     }
     */
    ReviewSummary: {
      /** Format: int64 */
      id: number;
      outlet: components["schemas"]["OutletRef"];
      source: string;
      /**
       * Format: date
       * @description Calendar date in the brand timezone.
       */
      review_date: string;
      rating: number;
      /** @description Shown as plain text, never as markup (tenet 6). */
      review_text: string;
      reviewer_name: string;
      /** @description Null while the review is untagged. */
      tags: components["schemas"]["Tags"] | null;
      /** @enum {string} */
      reply_status: "none" | "drafting" | "draft" | "replied";
    };
    /**
     * @example {
     *       "status": "draft",
     *       "draft_text": "Hi Karan, thank you for telling us about your visit on 3 October.",
     *       "prompt_version": 3,
     *       "reply_text": "Hi Karan, thank you for telling us about your visit on 3 October.",
     *       "edited": false,
     *       "replied_by": null,
     *       "replied_at": null,
     *       "updated_at": "2026-10-04T05:41:07.512Z"
     *     }
     */
    Reply: {
      /** @enum {string} */
      status: "drafting" | "draft" | "replied";
      /** @description What the model drafted; null while drafting or for a hand-written reply. */
      draft_text: string | null;
      /** @description The reply prompt version that drafted it. */
      prompt_version: number | null;
      /** @description The text the manager edits and approves; starts as the draft. */
      reply_text: string | null;
      /** @description True when reply_text differs from draft_text. */
      edited: boolean;
      /** @description The manager who approved it. */
      replied_by: components["schemas"]["UserRef"] | null;
      /** Format: date-time */
      replied_at: string | null;
      /**
       * Format: date-time
       * @description Send it back as based_on_updated_at on the next save or mark replied.
       */
      updated_at: string;
    };
    /**
     * @example {
     *       "reply_text": "Hi Karan, thank you for telling us about your visit on 3 October. This week we are working with our new floor team.",
     *       "based_on_updated_at": "2026-10-04T05:41:07.512Z"
     *     }
     */
    ReplySave: {
      reply_text: string;
      /**
       * Format: date-time
       * @description The reply's updated_at as the client last read it; null when the client saw no reply.
       */
      based_on_updated_at: string | null;
    };
    /**
     * @example {
     *       "id": 1497,
     *       "outlet": {
     *         "id": 1,
     *         "name": "Koramangala"
     *       },
     *       "source": "Google",
     *       "review_date": "2026-10-03",
     *       "rating": 2,
     *       "review_text": "Waited 50 minutes for a table even with a booking, and the food took another 30.",
     *       "reviewer_name": "Karan Malhotra",
     *       "tags": {
     *         "themes": [
     *           "wait_time",
     *           "staff",
     *           "food"
     *         ],
     *         "sentiment": "negative",
     *         "is_urgent": false,
     *         "urgent_reasons": [],
     *         "prompt_version": 2
     *       },
     *       "reply_status": "draft",
     *       "reply": {
     *         "status": "draft",
     *         "draft_text": "Hi Karan, thank you for telling us about your visit on 3 October.",
     *         "prompt_version": 3,
     *         "reply_text": "Hi Karan, thank you for telling us about your visit on 3 October.",
     *         "edited": false,
     *         "replied_by": null,
     *         "replied_at": null,
     *         "updated_at": "2026-10-04T05:41:07.512Z"
     *       },
     *       "outlet_managers": [
     *         {
     *           "id": 2,
     *           "name": "Arjun Mehta"
     *         }
     *       ],
     *       "can_reply": true
     *     }
     */
    ReviewDetail: components["schemas"]["ReviewSummary"] & {
      /** @description Null until a manager opens the review or writes a reply. */
      reply: components["schemas"]["Reply"] | null;
      /** @description Who may reply; empty means nobody is assigned to this outlet. */
      outlet_managers: components["schemas"]["UserRef"][];
      /** @description True only for an active manager of this review's outlet. */
      can_reply: boolean;
    };
    /**
     * @example {
     *       "start": "2026-09-28",
     *       "end": "2026-10-04"
     *     }
     */
    Week: {
      /**
       * Format: date
       * @description Monday.
       */
      start: string;
      /**
       * Format: date
       * @description Sunday.
       */
      end: string;
    };
    /**
     * @example {
     *       "week_start": "2026-09-28",
     *       "review_count": 21,
     *       "average_rating": 3.4,
     *       "positive": 6,
     *       "neutral": 4,
     *       "negative": 11,
     *       "untagged": 0,
     *       "replied": 9
     *     }
     */
    TrendWeek: {
      /** Format: date */
      week_start: string;
      review_count: number;
      /** @description Mean of the week's ratings to one decimal; null with no reviews. */
      average_rating: number | null;
      positive: number;
      neutral: number;
      negative: number;
      untagged: number;
      /** @description Reviews of that week marked replied. */
      replied: number;
    };
    /**
     * @example {
     *       "weeks": [
     *         "2026-07-13",
     *         "2026-07-20",
     *         "2026-07-27",
     *         "2026-08-03",
     *         "2026-08-10",
     *         "2026-08-17",
     *         "2026-08-24",
     *         "2026-08-31",
     *         "2026-09-07",
     *         "2026-09-14",
     *         "2026-09-21",
     *         "2026-09-28"
     *       ],
     *       "outlets": [
     *         {
     *           "outlet": {
     *             "id": 1,
     *             "name": "Koramangala"
     *           },
     *           "weeks": [
     *             {
     *               "week_start": "2026-09-21",
     *               "review_count": 12,
     *               "average_rating": 4.1,
     *               "positive": 7,
     *               "neutral": 2,
     *               "negative": 3,
     *               "untagged": 0,
     *               "replied": 12
     *             },
     *             {
     *               "week_start": "2026-09-28",
     *               "review_count": 21,
     *               "average_rating": 3.4,
     *               "positive": 6,
     *               "neutral": 4,
     *               "negative": 11,
     *               "untagged": 0,
     *               "replied": 9
     *             }
     *           ]
     *         }
     *       ]
     *     }
     */
    Trends: {
      /** @description The 12 week starts, oldest first. */
      weeks: string[];
      outlets: {
        outlet: components["schemas"]["OutletRef"];
        weeks: components["schemas"]["TrendWeek"][];
      }[];
    };
    /**
     * @example {
     *       "period": {
     *         "start": "2026-09-07",
     *         "end": "2026-10-04"
     *       },
     *       "themes": [
     *         {
     *           "code": "food",
     *           "label": "Food"
     *         },
     *         {
     *           "code": "wait_time",
     *           "label": "Wait time"
     *         }
     *       ],
     *       "rows": [
     *         {
     *           "outlet": {
     *             "id": 1,
     *             "name": "Koramangala"
     *           },
     *           "counts": {
     *             "food": 7,
     *             "wait_time": 19
     *           },
     *           "total": 26
     *         }
     *       ],
     *       "untagged_count": 0
     *     }
     */
    Heatmap: {
      period: {
        /** Format: date */
        start: string;
        /** Format: date */
        end: string;
      };
      themes: components["schemas"]["Theme"][];
      rows: {
        outlet: components["schemas"]["OutletRef"];
        /** @description Negative reviews per theme code; every configured theme is present. */
        counts: {
          [key: string]: number;
        };
        /** @description Sum of the outlet's theme counts, as the screen's Total column shows. */
        total: number;
      }[];
      /** @description Reviews in the period still untagged. */
      untagged_count: number;
    };
    /**
     * @example {
     *       "outlet": {
     *         "id": 1,
     *         "name": "Koramangala"
     *       },
     *       "theme": {
     *         "code": "wait_time",
     *         "label": "Wait time"
     *       },
     *       "previous_count": 3,
     *       "current_count": 11,
     *       "change": 8
     *     }
     */
    Mover: {
      outlet: components["schemas"]["OutletRef"];
      theme: components["schemas"]["Theme"];
      previous_count: number;
      current_count: number;
      /** @description current_count minus previous_count. */
      change: number;
    };
    /**
     * @example {
     *       "week": {
     *         "start": "2026-09-28",
     *         "end": "2026-10-04"
     *       },
     *       "previous_week": {
     *         "start": "2026-09-21",
     *         "end": "2026-09-27"
     *       },
     *       "review_count": 66,
     *       "untagged_count": 0,
     *       "movers": [
     *         {
     *           "outlet": {
     *             "id": 1,
     *             "name": "Koramangala"
     *           },
     *           "theme": {
     *             "code": "wait_time",
     *             "label": "Wait time"
     *           },
     *           "previous_count": 3,
     *           "current_count": 11,
     *           "change": 8
     *         }
     *       ]
     *     }
     */
    Movers: {
      week: components["schemas"]["Week"];
      previous_week: components["schemas"]["Week"];
      /** @description Reviews dated in the latest complete week. */
      review_count: number;
      /** @description Reviews dated in the two weeks still untagged. */
      untagged_count: number;
      movers: components["schemas"]["Mover"][];
    };
    /**
     * @example {
     *       "untagged_count": 5,
     *       "worker": "idle",
     *       "budget": {
     *         "state": "budget_exhausted",
     *         "spent_minor": 803,
     *         "limit_minor": 800,
     *         "currency": "USD"
     *       }
     *     }
     */
    TaggingStatus: {
      untagged_count: number;
      /**
       * @description paused when the operator switched TAGGING_ENABLED off.
       * @enum {string}
       */
      worker: "idle" | "running" | "paused";
      budget: {
        /**
         * @description Anything but ok means tagging and drafting have stopped.
         * @enum {string}
         */
        state: "ok" | "budget_exhausted" | "provider_credit_exhausted";
        /** @description Running total in cents, rounded up. */
        spent_minor: number;
        /** @description The USD 8.00 stop, 800 cents. */
        limit_minor: number;
        /** @enum {string} */
        currency: "USD";
      };
    };
    /**
     * @example {
     *       "id": 7,
     *       "status": "sent",
     *       "week_start": "2026-09-28",
     *       "week_end": "2026-10-04",
     *       "recipient_email": "ritika.rao@example.in",
     *       "untagged_count": 0,
     *       "subject": "Weekly digest, 28 Sep to 4 Oct 2026: Koramangala wait time up 8",
     *       "body": "Biggest mover: Koramangala, wait time. Negative reviews 3 to 11.",
     *       "sent_at": "2026-10-06T05:12:03Z",
     *       "failure_reason": null,
     *       "created_at": "2026-10-06T05:12:00Z"
     *     }
     */
    Digest: {
      /** Format: int64 */
      id: number;
      /** @enum {string} */
      status: "sending" | "sent" | "failed";
      /** Format: date */
      week_start: string;
      /** Format: date */
      week_end: string;
      /** Format: email */
      recipient_email: string;
      /** @description When above 0 the email's first line says movers and urgent reviews may be incomplete. */
      untagged_count: number;
      subject: string;
      /** @description The plain-text email as sent. */
      body: string;
      /** Format: date-time */
      sent_at: string | null;
      failure_reason: string | null;
      /** Format: date-time */
      created_at: string;
    };
  };
  responses: {
    /** @description Malformed request, or an unreadable CSV */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "csv_invalid",
         *         "message": "The file has no reviewer_name column.",
         *         "details": [
         *           {
         *             "field": "reviewer_name",
         *             "reason": "missing column"
         *           }
         *         ],
         *         "request_id": "req_01J9Z7"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description No session, or an expired one */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "unauthorized",
         *         "message": "Sign in again.",
         *         "request_id": "req_01J9Z8"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Wrong email or password */
    InvalidCredentials: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "invalid_credentials",
         *         "message": "Email or password is wrong.",
         *         "request_id": "req_01J9Z9"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description The caller's role may not take this action, or the write came from another origin */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "role_not_allowed",
         *         "message": "Only the outlet's manager can mark this review replied.",
         *         "request_id": "req_01J9ZA"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description The write came from a page on another origin; nothing was changed */
    CrossSiteRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "cross_site_request",
         *         "message": "This request came from another site and was refused. Open OutletOwl at its own address and try again.",
         *         "request_id": "req_01J9ZL"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description No such record for this caller */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "not_found",
         *         "message": "Review not found.",
         *         "request_id": "req_01J9ZB"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description The record's state does not allow this write */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "reply_changed",
         *         "message": "This reply changed since you opened it. Reload to see the newer text.",
         *         "request_id": "req_01J9ZC"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description The upload is over 5 MB */
    FileTooLarge: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "file_too_large",
         *         "message": "The file is over 5 MB. Split it into smaller files.",
         *         "request_id": "req_01J9ZD"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Wrong Content-Type */
    UnsupportedMediaType: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "unsupported_media_type",
         *         "message": "Send application/json.",
         *         "request_id": "req_01J9ZE"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Valid shape, but a field breaks a rule */
    ValidationFailed: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "validation_failed",
         *         "message": "reply_text must not be blank",
         *         "details": [
         *           {
         *             "field": "reply_text",
         *             "reason": "blank"
         *           }
         *         ],
         *         "request_id": "req_01J9ZF"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Unexpected failure; request_id is in the body */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "internal",
         *         "message": "Something failed on our side. Quote the request id.",
         *         "request_id": "req_01J9ZG"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description MailHog did not accept the digest; it is recorded as failed */
    MailUnavailable: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "mail_unavailable",
         *         "message": "The mail catcher (MailHog) did not answer. Start MailHog and generate the digest again.",
         *         "request_id": "req_01J9ZH"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description The model cannot draft now; the manager can write the reply by hand */
    DraftingUnavailable: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "budget_exhausted",
         *         "message": "Drafting is unavailable. The model budget is used up. Write the reply yourself.",
         *         "request_id": "req_01J9ZJ"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description PostgreSQL cannot be reached */
    DatabaseUnavailable: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "database_unavailable",
         *         "message": "The database is not reachable.",
         *         "request_id": "req_01J9ZK"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    /**
     * @description Client UUID, made once per user action. A repeat with the same key returns the first result and has no second side effect.
     * @example 0192b1c2-7f3a-7c4e-9a1b-2c3d4e5f6a7b
     */
    IdempotencyKey: string;
    /** @description Opaque; next_cursor from the previous page. */
    Cursor: string;
    Limit: number;
    /** @example 1497 */
    ReviewId: number;
  };
  requestBodies: never;
  headers: {
    /** @description Generated request id; the same value is in the error envelope and the server log line. */
    XRequestId: string;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "email": "arjun.mehta@example.in",
         *       "password": "correct-horse-battery"
         *     }
         */
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Signed in; the cookie is set */
      200: {
        headers: {
          /** @description outletowl_session, HttpOnly, SameSite=Strict, Path=/, Max-Age=28800. */
          "Set-Cookie"?: string;
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["InvalidCredentials"];
      403: components["responses"]["CrossSiteRequest"];
      415: components["responses"]["UnsupportedMediaType"];
      422: components["responses"]["ValidationFailed"];
      500: components["responses"]["InternalError"];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out; the cookie is cleared */
      204: {
        headers: {
          /** @description outletowl_session with Max-Age=0. */
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      403: components["responses"]["CrossSiteRequest"];
      500: components["responses"]["InternalError"];
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The caller */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["InternalError"];
    };
  };
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
      503: components["responses"]["DatabaseUnavailable"];
    };
  };
  listOutlets: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The outlets the caller may see */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "data": [
           *         {
           *           "id": 2,
           *           "name": "Indiranagar",
           *           "managers": [
           *             {
           *               "id": 3,
           *               "name": "Neha Kulkarni"
           *             }
           *           ],
           *           "review_count": 300,
           *           "untagged_count": 0,
           *           "created_at": "2026-04-06T04:30:00Z"
           *         }
           *       ]
           *     }
           */
          "application/json": {
            data: components["schemas"]["OutletSummary"][];
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["InternalError"];
    };
  };
  createOutlet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "name": "Electronic City"
         *     }
         */
        "application/json": components["schemas"]["OutletCreate"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          Location?: string;
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutletSummary"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      409: components["responses"]["Conflict"];
      415: components["responses"]["UnsupportedMediaType"];
      422: components["responses"]["ValidationFailed"];
      500: components["responses"]["InternalError"];
    };
  };
  createImport: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Client UUID, made once per user action. A repeat with the same key returns the first result and has no second side effect.
         * @example 0192b1c2-7f3a-7c4e-9a1b-2c3d4e5f6a7b
         */
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["ImportUpload"];
      };
    };
    responses: {
      /** @description Imported; a repeat with the same Idempotency-Key returns this result again */
      201: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportResult"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["FileTooLarge"];
      415: components["responses"]["UnsupportedMediaType"];
      500: components["responses"]["InternalError"];
    };
  };
  listThemes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The themes in display order */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "data": [
           *         {
           *           "code": "food",
           *           "label": "Food"
           *         },
           *         {
           *           "code": "wait_time",
           *           "label": "Wait time"
           *         },
           *         {
           *           "code": "staff",
           *           "label": "Staff"
           *         },
           *         {
           *           "code": "cleanliness",
           *           "label": "Cleanliness"
           *         },
           *         {
           *           "code": "price",
           *           "label": "Price"
           *         }
           *       ]
           *     }
           */
          "application/json": {
            data: components["schemas"]["Theme"][];
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["InternalError"];
    };
  };
  listReviews: {
    parameters: {
      query?: {
        /** @description Opaque; next_cursor from the previous page. */
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
        /** @description Case-insensitive substring of the review text or the reviewer name. */
        q?: string;
        "filter[outlet_id]"?: number;
        /** @description A theme code from GET /themes; an unknown code is 422. */
        "filter[theme]"?: string;
        "filter[sentiment]"?: components["schemas"]["Sentiment"];
        "filter[is_urgent]"?: boolean;
        /** @description none means no draft yet (drafting included), draft means a draft is ready, replied means approved. */
        "filter[reply_status]"?: "none" | "draft" | "replied";
        "filter[review_date][gte]"?: string;
        "filter[review_date][lte]"?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description One page */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "data": [
           *         {
           *           "id": 1497,
           *           "outlet": {
           *             "id": 1,
           *             "name": "Koramangala"
           *           },
           *           "source": "Google",
           *           "review_date": "2026-10-03",
           *           "rating": 2,
           *           "review_text": "Waited 50 minutes for a table even with a booking, and the food took another 30.",
           *           "reviewer_name": "Karan Malhotra",
           *           "tags": {
           *             "themes": [
           *               "wait_time",
           *               "staff",
           *               "food"
           *             ],
           *             "sentiment": "negative",
           *             "is_urgent": false,
           *             "urgent_reasons": [],
           *             "prompt_version": 2
           *           },
           *           "reply_status": "draft"
           *         }
           *       ],
           *       "page": {
           *         "next_cursor": "eyJkIjoiMjAyNi0xMC0wMyIsImlkIjoxNDk3fQ",
           *         "has_more": true
           *       },
           *       "total": 1500
           *     }
           */
          "application/json": {
            data: components["schemas"]["ReviewSummary"][];
            page: components["schemas"]["Page"];
            total: number;
          };
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["NotFound"];
      422: components["responses"]["ValidationFailed"];
      500: components["responses"]["InternalError"];
    };
  };
  getReview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 1497 */
        review_id: components["parameters"]["ReviewId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The review */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewDetail"];
        };
      };
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalError"];
    };
  };
  createReplyDraft: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 1497 */
        review_id: components["parameters"]["ReviewId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The reply, stored or just drafted */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Reply"];
        };
      };
      /** @description Another request is drafting this review; call again after Retry-After seconds */
      202: {
        headers: {
          "Retry-After"?: number;
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "drafting",
           *       "draft_text": null,
           *       "prompt_version": null,
           *       "reply_text": null,
           *       "edited": false,
           *       "replied_by": null,
           *       "replied_at": null,
           *       "updated_at": "2026-10-04T05:49:58.120Z"
           *     }
           */
          "application/json": components["schemas"]["Reply"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalError"];
      503: components["responses"]["DraftingUnavailable"];
    };
  };
  saveReply: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 1497 */
        review_id: components["parameters"]["ReviewId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReplySave"];
      };
    };
    responses: {
      /** @description The saved reply, with its new updated_at */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Reply"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      415: components["responses"]["UnsupportedMediaType"];
      422: components["responses"]["ValidationFailed"];
      500: components["responses"]["InternalError"];
    };
  };
  markReplied: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 1497 */
        review_id: components["parameters"]["ReviewId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReplySave"];
      };
    };
    responses: {
      /** @description The replied reply */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "replied",
           *       "draft_text": "Hi Karan, thank you for telling us about your visit on 3 October.",
           *       "prompt_version": 3,
           *       "reply_text": "Hi Karan, thank you for telling us about your visit on 3 October. This week we are working with our new floor team.",
           *       "edited": true,
           *       "replied_by": {
           *         "id": 2,
           *         "name": "Arjun Mehta"
           *       },
           *       "replied_at": "2026-10-04T05:50:00Z",
           *       "updated_at": "2026-10-04T05:50:00Z"
           *     }
           */
          "application/json": components["schemas"]["Reply"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      415: components["responses"]["UnsupportedMediaType"];
      422: components["responses"]["ValidationFailed"];
      500: components["responses"]["InternalError"];
    };
  };
  getTrends: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The trends */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Trends"];
        };
      };
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["InternalError"];
    };
  };
  getHeatmap: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The heatmap */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Heatmap"];
        };
      };
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["InternalError"];
    };
  };
  getMovers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The movers */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Movers"];
        };
      };
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["InternalError"];
    };
  };
  getTaggingStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The status */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaggingStatus"];
        };
      };
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["InternalError"];
    };
  };
  createDigest: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Client UUID, made once per user action. A repeat with the same key returns the first result and has no second side effect.
         * @example 0192b1c2-7f3a-7c4e-9a1b-2c3d4e5f6a7b
         */
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sent */
      201: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Digest"];
        };
      };
      /** @description A repeat of a request whose digest is still marked sending; nothing is sent again */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "id": 7,
           *       "status": "sending",
           *       "week_start": "2026-09-28",
           *       "week_end": "2026-10-04",
           *       "recipient_email": "ritika.rao@example.in",
           *       "untagged_count": 0,
           *       "subject": "Weekly digest, 28 Sep to 4 Oct 2026: Koramangala wait time up 8",
           *       "body": "Biggest mover: Koramangala, wait time. Negative reviews 3 to 11.",
           *       "sent_at": null,
           *       "failure_reason": null,
           *       "created_at": "2026-10-06T05:12:00Z"
           *     }
           */
          "application/json": components["schemas"]["Digest"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      500: components["responses"]["InternalError"];
      502: components["responses"]["MailUnavailable"];
    };
  };
}
