// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const negativeThemeCounts = `-- name: NegativeThemeCounts :many
SELECT r.outlet_id,
       date_trunc('week', r.review_date)::date AS week_start,
       theme::text AS theme,
       count(*)::integer AS negative
FROM reviews r
JOIN review_tags t ON t.review_id = r.id
CROSS JOIN LATERAL unnest(t.themes) AS theme
WHERE ($1::boolean OR r.outlet_id = $2::bigint)
  AND t.sentiment = 'negative'
  AND r.review_date BETWEEN $3::date AND $4::date
GROUP BY r.outlet_id, week_start, theme
`

type NegativeThemeCountsParams struct {
	AllOutlets    bool        `json:"all_outlets"`
	ScopeOutletID int64       `json:"scope_outlet_id"`
	DateFrom      pgtype.Date `json:"date_from"`
	DateTo        pgtype.Date `json:"date_to"`
}

type NegativeThemeCountsRow struct {
	OutletID  int64       `json:"outlet_id"`
	WeekStart pgtype.Date `json:"week_start"`
	Theme     string      `json:"theme"`
	Negative  int32       `json:"negative"`
}

func (q *Queries) NegativeThemeCounts(ctx context.Context, arg NegativeThemeCountsParams) ([]NegativeThemeCountsRow, error) {
	rows, err := q.db.Query(ctx, negativeThemeCounts,
		arg.AllOutlets,
		arg.ScopeOutletID,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NegativeThemeCountsRow
	for rows.Next() {
		var i NegativeThemeCountsRow
		if err := rows.Scan(
			&i.OutletID,
			&i.WeekStart,
			&i.Theme,
			&i.Negative,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewCounts = `-- name: ReviewCounts :one
SELECT count(*)::integer AS total,
       (count(*) FILTER (WHERE NOT EXISTS (SELECT 1 FROM review_tags t WHERE t.review_id = r.id)))::integer AS untagged
FROM reviews r
WHERE ($1::boolean OR r.outlet_id = $2::bigint)
  AND r.review_date BETWEEN $3::date AND $4::date
`

type ReviewCountsParams struct {
	AllOutlets    bool        `json:"all_outlets"`
	ScopeOutletID int64       `json:"scope_outlet_id"`
	DateFrom      pgtype.Date `json:"date_from"`
	DateTo        pgtype.Date `json:"date_to"`
}

type ReviewCountsRow struct {
	Total    int32 `json:"total"`
	Untagged int32 `json:"untagged"`
}

func (q *Queries) ReviewCounts(ctx context.Context, arg ReviewCountsParams) (ReviewCountsRow, error) {
	row := q.db.QueryRow(ctx, reviewCounts,
		arg.AllOutlets,
		arg.ScopeOutletID,
		arg.DateFrom,
		arg.DateTo,
	)
	var i ReviewCountsRow
	err := row.Scan(&i.Total, &i.Untagged)
	return i, err
}

const untaggedCount = `-- name: UntaggedCount :one
SELECT count(*)::integer
FROM reviews r
WHERE ($1::boolean OR r.outlet_id = $2::bigint)
  AND NOT EXISTS (SELECT 1 FROM review_tags t WHERE t.review_id = r.id)
`

type UntaggedCountParams struct {
	AllOutlets    bool  `json:"all_outlets"`
	ScopeOutletID int64 `json:"scope_outlet_id"`
}

// The tagging status; review_tags_pkey anti-join.
func (q *Queries) UntaggedCount(ctx context.Context, arg UntaggedCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, untaggedCount, arg.AllOutlets, arg.ScopeOutletID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const weeklyOutletStats = `-- name: WeeklyOutletStats :many

SELECT r.outlet_id,
       date_trunc('week', r.review_date)::date AS week_start,
       count(*)::integer AS review_count,
       round(avg(r.rating), 1)::float8 AS average_rating,
       (count(*) FILTER (WHERE t.sentiment = 'positive'))::integer AS positive,
       (count(*) FILTER (WHERE t.sentiment = 'neutral'))::integer AS neutral,
       (count(*) FILTER (WHERE t.sentiment = 'negative'))::integer AS negative,
       (count(*) FILTER (WHERE t.review_id IS NULL))::integer AS untagged,
       (count(*) FILTER (WHERE rp.status = 'replied'))::integer AS replied
FROM reviews r
LEFT JOIN review_tags t ON t.review_id = r.id
LEFT JOIN replies rp ON rp.review_id = r.id
WHERE ($1::boolean OR r.outlet_id = $2::bigint)
  AND r.review_date BETWEEN $3::date AND $4::date
GROUP BY r.outlet_id, week_start
`

type WeeklyOutletStatsParams struct {
	AllOutlets    bool        `json:"all_outlets"`
	ScopeOutletID int64       `json:"scope_outlet_id"`
	DateFrom      pgtype.Date `json:"date_from"`
	DateTo        pgtype.Date `json:"date_to"`
}

type WeeklyOutletStatsRow struct {
	OutletID      int64       `json:"outlet_id"`
	WeekStart     pgtype.Date `json:"week_start"`
	ReviewCount   int32       `json:"review_count"`
	AverageRating float64     `json:"average_rating"`
	Positive      int32       `json:"positive"`
	Neutral       int32       `json:"neutral"`
	Negative      int32       `json:"negative"`
	Untagged      int32       `json:"untagged"`
	Replied       int32       `json:"replied"`
}

// Dashboard reports (phase 4 LLD section 5). Every statement is scoped by
// all_outlets OR outlet_id (tenet 3); weeks start on Monday
// (date_trunc('week')). Known full scans for the brand admin at about 10^4 rows.
func (q *Queries) WeeklyOutletStats(ctx context.Context, arg WeeklyOutletStatsParams) ([]WeeklyOutletStatsRow, error) {
	rows, err := q.db.Query(ctx, weeklyOutletStats,
		arg.AllOutlets,
		arg.ScopeOutletID,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeeklyOutletStatsRow
	for rows.Next() {
		var i WeeklyOutletStatsRow
		if err := rows.Scan(
			&i.OutletID,
			&i.WeekStart,
			&i.ReviewCount,
			&i.AverageRating,
			&i.Positive,
			&i.Neutral,
			&i.Negative,
			&i.Untagged,
			&i.Replied,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
