// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digests.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeBrandAdminEmail = `-- name: ActiveBrandAdminEmail :one
SELECT email FROM users WHERE role = 'brand_admin' AND removed_at IS NULL
`

// The one active brand admin (uq_users_one_brand_admin), the digest's recipient.
func (q *Queries) ActiveBrandAdminEmail(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, activeBrandAdminEmail)
	var email string
	err := row.Scan(&email)
	return email, err
}

const claimDigest = `-- name: ClaimDigest :one
INSERT INTO digests (request_id, week_start, recipient_email, untagged_count, subject, body)
VALUES (($1::text)::uuid, $2, $3, $4,
        $5, $6)
ON CONFLICT (request_id) DO NOTHING
RETURNING id, created_at
`

type ClaimDigestParams struct {
	RequestID      string      `json:"request_id"`
	WeekStart      pgtype.Date `json:"week_start"`
	RecipientEmail string      `json:"recipient_email"`
	UntaggedCount  int32       `json:"untagged_count"`
	Subject        string      `json:"subject"`
	Body           string      `json:"body"`
}

type ClaimDigestRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

// No row when the request id exists; waits for one still in flight.
func (q *Queries) ClaimDigest(ctx context.Context, arg ClaimDigestParams) (ClaimDigestRow, error) {
	row := q.db.QueryRow(ctx, claimDigest,
		arg.RequestID,
		arg.WeekStart,
		arg.RecipientEmail,
		arg.UntaggedCount,
		arg.Subject,
		arg.Body,
	)
	var i ClaimDigestRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getDigestByRequestID = `-- name: GetDigestByRequestID :one

SELECT id, status::text AS status, week_start, recipient_email, untagged_count, subject, body, failure_reason, sent_at, created_at
FROM digests
WHERE request_id = ($1::text)::uuid
`

type GetDigestByRequestIDRow struct {
	ID             int64       `json:"id"`
	Status         string      `json:"status"`
	WeekStart      pgtype.Date `json:"week_start"`
	RecipientEmail string      `json:"recipient_email"`
	UntaggedCount  int32       `json:"untagged_count"`
	Subject        string      `json:"subject"`
	Body           string      `json:"body"`
	FailureReason  *string     `json:"failure_reason"`
	SentAt         *time.Time  `json:"sent_at"`
	CreatedAt      time.Time   `json:"created_at"`
}

// Digests: claimed under the request id before SMTP, then sent or failed
// (HLD flow C, data model section 5); uq_digests_request_id.
func (q *Queries) GetDigestByRequestID(ctx context.Context, requestID string) (GetDigestByRequestIDRow, error) {
	row := q.db.QueryRow(ctx, getDigestByRequestID, requestID)
	var i GetDigestByRequestIDRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.WeekStart,
		&i.RecipientEmail,
		&i.UntaggedCount,
		&i.Subject,
		&i.Body,
		&i.FailureReason,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const markDigestFailed = `-- name: MarkDigestFailed :exec
UPDATE digests SET status = 'failed', failure_reason = $1::text, updated_at = now()
WHERE id = $2 AND status = 'sending'
`

type MarkDigestFailedParams struct {
	Reason string `json:"reason"`
	ID     int64  `json:"id"`
}

func (q *Queries) MarkDigestFailed(ctx context.Context, arg MarkDigestFailedParams) error {
	_, err := q.db.Exec(ctx, markDigestFailed, arg.Reason, arg.ID)
	return err
}

const markDigestSent = `-- name: MarkDigestSent :one
UPDATE digests SET status = 'sent', sent_at = now(), updated_at = now()
WHERE id = $1 AND status = 'sending'
RETURNING sent_at
`

func (q *Queries) MarkDigestSent(ctx context.Context, id int64) (*time.Time, error) {
	row := q.db.QueryRow(ctx, markDigestSent, id)
	var sent_at *time.Time
	err := row.Scan(&sent_at)
	return sent_at, err
}
