// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImport = `-- name: CreateImport :one
INSERT INTO imports (request_id, file_name)
VALUES (($1::text)::uuid, $2)
ON CONFLICT (request_id) DO NOTHING
RETURNING id, created_at
`

type CreateImportParams struct {
	RequestID string `json:"request_id"`
	FileName  string `json:"file_name"`
}

type CreateImportRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

// No row when the request id exists; the insert waits for an import with
// the same id still in flight (uq_imports_request_id).
func (q *Queries) CreateImport(ctx context.Context, arg CreateImportParams) (CreateImportRow, error) {
	row := q.db.QueryRow(ctx, createImport, arg.RequestID, arg.FileName)
	var i CreateImportRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getImportByRequestID = `-- name: GetImportByRequestID :one

SELECT id, file_name, imported_count, duplicate_count, rejected_count, created_at
FROM imports
WHERE request_id = ($1::text)::uuid
`

type GetImportByRequestIDRow struct {
	ID             int64     `json:"id"`
	FileName       string    `json:"file_name"`
	ImportedCount  int32     `json:"imported_count"`
	DuplicateCount int32     `json:"duplicate_count"`
	RejectedCount  int32     `json:"rejected_count"`
	CreatedAt      time.Time `json:"created_at"`
}

// Imports: the CSV upload and its result (phase 3 LLD, section 7).
// A repeat of an upload finds the first result; uq_imports_request_id.
func (q *Queries) GetImportByRequestID(ctx context.Context, requestID string) (GetImportByRequestIDRow, error) {
	row := q.db.QueryRow(ctx, getImportByRequestID, requestID)
	var i GetImportByRequestIDRow
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.ImportedCount,
		&i.DuplicateCount,
		&i.RejectedCount,
		&i.CreatedAt,
	)
	return i, err
}

const insertImportRejections = `-- name: InsertImportRejections :exec
INSERT INTO import_rejections (import_id, row_number, reason)
SELECT $1::bigint, ($2::integer[])[i], ($3::text[])[i]
FROM generate_subscripts($2::integer[], 1) AS i
`

type InsertImportRejectionsParams struct {
	ImportID   int64    `json:"import_id"`
	RowNumbers []int32  `json:"row_numbers"`
	Reasons    []string `json:"reasons"`
}

func (q *Queries) InsertImportRejections(ctx context.Context, arg InsertImportRejectionsParams) error {
	_, err := q.db.Exec(ctx, insertImportRejections, arg.ImportID, arg.RowNumbers, arg.Reasons)
	return err
}

const insertReviews = `-- name: InsertReviews :many
INSERT INTO reviews (outlet_id, import_id, source, review_date, rating, review_text, reviewer_name)
SELECT ($1::bigint[])[i], $2::bigint, ($3::text[])[i],
       ($4::date[])[i], ($5::smallint[])[i],
       ($6::text[])[i], ($7::text[])[i]
FROM generate_subscripts($1::bigint[], 1) AS i
ORDER BY i
ON CONFLICT (outlet_id, source, review_date, reviewer_name, md5(review_text)) DO NOTHING
RETURNING id
`

type InsertReviewsParams struct {
	OutletIds     []int64       `json:"outlet_ids"`
	ImportID      int64         `json:"import_id"`
	Sources       []string      `json:"sources"`
	ReviewDates   []pgtype.Date `json:"review_dates"`
	Ratings       []int16       `json:"ratings"`
	ReviewTexts   []string      `json:"review_texts"`
	ReviewerNames []string      `json:"reviewer_names"`
}

// The valid rows of one import, in file order so review ids follow the file.
// A row already stored (same outlet, source, date, reviewer and text) returns
// nothing and is counted as a duplicate; uq_reviews_natural_key.
func (q *Queries) InsertReviews(ctx context.Context, arg InsertReviewsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, insertReviews,
		arg.OutletIds,
		arg.ImportID,
		arg.Sources,
		arg.ReviewDates,
		arg.Ratings,
		arg.ReviewTexts,
		arg.ReviewerNames,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportRejections = `-- name: ListImportRejections :many
SELECT row_number, reason
FROM import_rejections
WHERE import_id = $1
ORDER BY row_number
`

type ListImportRejectionsRow struct {
	RowNumber int32  `json:"row_number"`
	Reason    string `json:"reason"`
}

// The rejected rows of one import, in row order; import_rejections_pkey.
func (q *Queries) ListImportRejections(ctx context.Context, importID int64) ([]ListImportRejectionsRow, error) {
	rows, err := q.db.Query(ctx, listImportRejections, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportRejectionsRow
	for rows.Next() {
		var i ListImportRejectionsRow
		if err := rows.Scan(&i.RowNumber, &i.Reason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setImportCounts = `-- name: SetImportCounts :exec
UPDATE imports
SET imported_count = $1, duplicate_count = $2,
    rejected_count = $3
WHERE id = $4
`

type SetImportCountsParams struct {
	ImportedCount  int32 `json:"imported_count"`
	DuplicateCount int32 `json:"duplicate_count"`
	RejectedCount  int32 `json:"rejected_count"`
	ID             int64 `json:"id"`
}

func (q *Queries) SetImportCounts(ctx context.Context, arg SetImportCountsParams) error {
	_, err := q.db.Exec(ctx, setImportCounts,
		arg.ImportedCount,
		arg.DuplicateCount,
		arg.RejectedCount,
		arg.ID,
	)
	return err
}
