// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BudgetModelCallOutcome string

const (
	BudgetModelCallOutcomeReserved BudgetModelCallOutcome = "reserved"
	BudgetModelCallOutcomeSettled  BudgetModelCallOutcome = "settled"
	BudgetModelCallOutcomeFailed   BudgetModelCallOutcome = "failed"
)

func (e *BudgetModelCallOutcome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BudgetModelCallOutcome(s)
	case string:
		*e = BudgetModelCallOutcome(s)
	default:
		return fmt.Errorf("unsupported scan type for BudgetModelCallOutcome: %T", src)
	}
	return nil
}

type NullBudgetModelCallOutcome struct {
	BudgetModelCallOutcome BudgetModelCallOutcome `json:"budget_model_call_outcome"`
	Valid                  bool                   `json:"valid"` // Valid is true if BudgetModelCallOutcome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBudgetModelCallOutcome) Scan(value interface{}) error {
	if value == nil {
		ns.BudgetModelCallOutcome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BudgetModelCallOutcome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBudgetModelCallOutcome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BudgetModelCallOutcome), nil
}

type BudgetModelCallPurpose string

const (
	BudgetModelCallPurposeTagging        BudgetModelCallPurpose = "tagging"
	BudgetModelCallPurposeDrafting       BudgetModelCallPurpose = "drafting"
	BudgetModelCallPurposeEvaluation     BudgetModelCallPurpose = "evaluation"
	BudgetModelCallPurposeToneCheck      BudgetModelCallPurpose = "tone_check"
	BudgetModelCallPurposeReconciliation BudgetModelCallPurpose = "reconciliation"
)

func (e *BudgetModelCallPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BudgetModelCallPurpose(s)
	case string:
		*e = BudgetModelCallPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for BudgetModelCallPurpose: %T", src)
	}
	return nil
}

type NullBudgetModelCallPurpose struct {
	BudgetModelCallPurpose BudgetModelCallPurpose `json:"budget_model_call_purpose"`
	Valid                  bool                   `json:"valid"` // Valid is true if BudgetModelCallPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBudgetModelCallPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.BudgetModelCallPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BudgetModelCallPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBudgetModelCallPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BudgetModelCallPurpose), nil
}

type DigestStatus string

const (
	DigestStatusSending DigestStatus = "sending"
	DigestStatusSent    DigestStatus = "sent"
	DigestStatusFailed  DigestStatus = "failed"
)

func (e *DigestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DigestStatus(s)
	case string:
		*e = DigestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DigestStatus: %T", src)
	}
	return nil
}

type NullDigestStatus struct {
	DigestStatus DigestStatus `json:"digest_status"`
	Valid        bool         `json:"valid"` // Valid is true if DigestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDigestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DigestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DigestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDigestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DigestStatus), nil
}

type ReplyStatus string

const (
	ReplyStatusDrafting ReplyStatus = "drafting"
	ReplyStatusDraft    ReplyStatus = "draft"
	ReplyStatusReplied  ReplyStatus = "replied"
)

func (e *ReplyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReplyStatus(s)
	case string:
		*e = ReplyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReplyStatus: %T", src)
	}
	return nil
}

type NullReplyStatus struct {
	ReplyStatus ReplyStatus `json:"reply_status"`
	Valid       bool        `json:"valid"` // Valid is true if ReplyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReplyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReplyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReplyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReplyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReplyStatus), nil
}

type Sentiment string

const (
	SentimentPositive Sentiment = "positive"
	SentimentNeutral  Sentiment = "neutral"
	SentimentNegative Sentiment = "negative"
)

func (e *Sentiment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Sentiment(s)
	case string:
		*e = Sentiment(s)
	default:
		return fmt.Errorf("unsupported scan type for Sentiment: %T", src)
	}
	return nil
}

type NullSentiment struct {
	Sentiment Sentiment `json:"sentiment"`
	Valid     bool      `json:"valid"` // Valid is true if Sentiment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSentiment) Scan(value interface{}) error {
	if value == nil {
		ns.Sentiment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Sentiment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSentiment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Sentiment), nil
}

type UserRole string

const (
	UserRoleBrandAdmin    UserRole = "brand_admin"
	UserRoleOutletManager UserRole = "outlet_manager"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

// Every live model call and its cost; the running total. Never truncated or dropped. Serves US-02-001, US-02-002, US-02-004, US-02-005.
type BudgetModelCall struct {
	// Surrogate key; the gateway settles the row it reserved by this id.
	ID int64 `json:"id"`
	// tagging, drafting, evaluation, tone_check, or reconciliation for a start-up adjustment.
	Purpose BudgetModelCallPurpose `json:"purpose"`
	// Model identifier sent to OpenRouter; null only on a reconciliation row.
	Model *string `json:"model"`
	// Number of the prompt version sent; the purpose says which prompt.
	PromptVersion *int32 `json:"prompt_version"`
	// Input tokens OpenRouter reported; null until the call settles.
	InputTokens *int32 `json:"input_tokens"`
	// Output tokens OpenRouter reported; null until the call settles.
	OutputTokens *int32 `json:"output_tokens"`
	// Worst-case price reserved before the call (input plus max_tokens); counts until settled.
	ReservedCostUsd pgtype.Numeric `json:"reserved_cost_usd"`
	// usage.cost from the response, in USD; replaces the reserved price in the total.
	SettledCostUsd pgtype.Numeric `json:"settled_cost_usd"`
	// reserved while in flight, settled with a response, failed without one (stays at the reserved price).
	Outcome BudgetModelCallOutcome `json:"outcome"`
	// When the call was reserved, which is the time the log shows.
	CreatedAt time.Time `json:"created_at"`
	// When the call settled or failed.
	UpdatedAt time.Time `json:"updated_at"`
}

// One generated weekly digest. Serves US-01-009.
type Digest struct {
	// Surrogate key.
	ID int64 `json:"id"`
	// Client-made id; a repeat returns this digest and never sends again (tenet 8).
	RequestID pgtype.UUID `json:"request_id"`
	// sending before SMTP is called, then sent or failed.
	Status DigestStatus `json:"status"`
	// Monday of the latest complete week the digest covers, in the brand timezone.
	WeekStart pgtype.Date `json:"week_start"`
	// Address the one email went to: the brand admin. [personal data]
	RecipientEmail string `json:"recipient_email"`
	// Reviews dated in the two compared weeks that were still untagged.
	UntaggedCount int32 `json:"untagged_count"`
	// Email subject as sent.
	Subject string `json:"subject"`
	// Email body as composed, quoting urgent reviews. [personal data]
	Body string `json:"body"`
	// The SMTP error shown to the admin when sending failed.
	FailureReason *string `json:"failure_reason"`
	// When MailHog accepted the email.
	SentAt *time.Time `json:"sent_at"`
	// When the digest was generated and claimed.
	CreatedAt time.Time `json:"created_at"`
	// Last status change.
	UpdatedAt time.Time `json:"updated_at"`
}

// One CSV upload and its result. Serves US-01-002.
type Import struct {
	// Surrogate key; reviews record the import that brought them in.
	ID int64 `json:"id"`
	// Client-made id; a repeat with the same id returns this result and imports nothing (tenet 8).
	RequestID pgtype.UUID `json:"request_id"`
	// Name of the uploaded file, shown with the result.
	FileName string `json:"file_name"`
	// Rows stored as new reviews; set before the import commits.
	ImportedCount int32 `json:"imported_count"`
	// Rows skipped because the same review was already imported.
	DuplicateCount int32 `json:"duplicate_count"`
	// Rows rejected; each is listed in import_rejections.
	RejectedCount int32 `json:"rejected_count"`
	// When the import committed.
	CreatedAt time.Time `json:"created_at"`
}

// A CSV row an import rejected. Serves US-01-002.
type ImportRejection struct {
	// The import that rejected the row.
	ImportID int64 `json:"import_id"`
	// Row number in the file, counted as the admin sees it in a spreadsheet.
	RowNumber int32 `json:"row_number"`
	// Why the row was rejected, worded so the admin can fix it.
	Reason string `json:"reason"`
}

// One location of the brand. Serves US-01-001, US-01-002, US-01-005, US-01-006, US-01-007, US-00-001.
type Outlet struct {
	// Surrogate key; reviews and managers reference it.
	ID int64 `json:"id"`
	// Outlet name as the admin typed it; the CSV outlet column must match it, ignoring case.
	Name string `json:"name"`
	// When the outlet was added.
	CreatedAt time.Time `json:"created_at"`
	// Last change to this row.
	UpdatedAt time.Time `json:"updated_at"`
}

// The draft and the approved reply of a review. Serves US-00-002, US-00-003, US-01-008, US-02-002.
type Reply struct {
	// The review replied to; the primary key lets only one request claim the draft.
	ReviewID int64 `json:"review_id"`
	// drafting while the model call runs, draft while editable, replied once a manager approved it.
	Status ReplyStatus `json:"status"`
	// The text the model drafted, kept as drafted; null while drafting or when written by hand. [personal data]
	DraftText *string `json:"draft_text"`
	// Number of the reply prompt version that drafted draft_text; null without a model draft.
	PromptVersion *int32 `json:"prompt_version"`
	// The text the manager edits and approves; starts as the draft. [personal data]
	ReplyText *string `json:"reply_text"`
	// The outlet manager who marked it replied, which is the approval.
	RepliedBy *int64 `json:"replied_by"`
	// When the manager marked it replied.
	RepliedAt *time.Time `json:"replied_at"`
	// When the draft was claimed or the reply first written.
	CreatedAt time.Time `json:"created_at"`
	// Last change; a drafting claim older than 60 seconds may be taken over.
	UpdatedAt time.Time `json:"updated_at"`
}

// One customer review of one outlet. Serves US-01-002, US-01-003, US-01-005 to US-01-009, US-00-001, US-00-002, US-02-006.
type Review struct {
	// Integer id; the id the tagging batch sends and every result line must carry (tenet 4).
	ID int64 `json:"id"`
	// The outlet reviewed, matched from the CSV outlet column; the outlet scope filters on it.
	OutletID int64 `json:"outlet_id"`
	// The import that brought the review in; null for reviews the seed command wrote.
	ImportID *int64 `json:"import_id"`
	// Where the review was written, as the CSV source column says.
	Source string `json:"source"`
	// Calendar date of the review; weeks are Monday to Sunday in the brand timezone.
	ReviewDate pgtype.Date `json:"review_date"`
	// Star rating, a whole number from 1 to 5.
	Rating int16 `json:"rating"`
	// The review as written, kept unchanged. [personal data]
	ReviewText string `json:"review_text"`
	// Name of the person who wrote the review. [personal data]
	ReviewerName string `json:"reviewer_name"`
	// When the review was stored.
	CreatedAt time.Time `json:"created_at"`
}

// The stored tag result of a review; written once, never re-tagged. Serves US-01-003 to US-01-009, US-02-002.
type ReviewTag struct {
	// The review the result line named; one result per review.
	ReviewID int64 `json:"review_id"`
	// Theme codes from the configured list; zero, one or several.
	Themes []string `json:"themes"`
	// One label: positive, neutral or negative.
	Sentiment Sentiment `json:"sentiment"`
	// True when the review concerns food safety, harassment or a legal threat; true exactly when urgent_reasons is not empty.
	IsUrgent bool `json:"is_urgent"`
	// Why the review is urgent: food_safety, harassment, legal_threat; several allowed, none repeated, empty when not urgent.
	UrgentReasons []string `json:"urgent_reasons"`
	// Number of the tagging prompt version that produced this result.
	PromptVersion int32 `json:"prompt_version"`
	// When the result was stored.
	CreatedAt time.Time `json:"created_at"`
}

// An account from the users file; one brand admin and outlet managers. Serves US-00-001, US-00-003, US-01-001, US-01-009, US-02-006.
type User struct {
	// Surrogate key; the only identity the JWT carries (ADR-0007).
	ID int64 `json:"id"`
	// Sign-in name and the digest recipient address. [personal data]
	Email string `json:"email"`
	// Name shown in the top bar and beside a reply the manager marked replied. [personal data]
	Name string `json:"name"`
	// brand_admin or outlet_manager, re-read on every request (ADR-0007).
	Role UserRole `json:"role"`
	// The one outlet an outlet manager may see and act on; null for the brand admin.
	OutletID *int64 `json:"outlet_id"`
	// bcrypt hash from the users file; never the password.
	PasswordHash string `json:"password_hash"`
	// Set when the account left the users file; sign-in is refused, the row stays so replies keep their manager.
	RemovedAt *time.Time `json:"removed_at"`
	// When the account was first loaded.
	CreatedAt time.Time `json:"created_at"`
	// Last change from the users file.
	UpdatedAt time.Time `json:"updated_at"`
}
