// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_calls.sql

package store

import (
	"context"
)

const failModelCall = `-- name: FailModelCall :execrows
UPDATE budget.model_calls
SET outcome = 'failed', updated_at = now()
WHERE id = $1 AND outcome = 'reserved'
`

func (q *Queries) FailModelCall(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, failModelCall, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertReconciliation = `-- name: InsertReconciliation :many
INSERT INTO budget.model_calls (purpose, reserved_cost_usd, settled_cost_usd, input_tokens, output_tokens, outcome)
SELECT 'reconciliation', d.diff, d.diff, 0, 0, 'settled'
FROM (
    -- Rounded to the column's scale first, so a provider figure with more
    -- than 8 decimals never inserts a row worth 0.00000000.
    SELECT round(CAST($1::text AS numeric) - coalesce(sum(coalesce(settled_cost_usd, reserved_cost_usd)), 0), 8) AS diff
    FROM budget.model_calls
) d
WHERE d.diff > 0
RETURNING settled_cost_usd::text AS added_usd
`

// Inserts the difference when the provider's usage is higher than the local
// total; nothing otherwise. Only the server calls it, once at start.
func (q *Queries) InsertReconciliation(ctx context.Context, providerUsageUsd string) ([]string, error) {
	rows, err := q.db.Query(ctx, insertReconciliation, providerUsageUsd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var added_usd string
		if err := rows.Scan(&added_usd); err != nil {
			return nil, err
		}
		items = append(items, added_usd)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveModelCall = `-- name: ReserveModelCall :one

INSERT INTO budget.model_calls (purpose, model, prompt_version, reserved_cost_usd)
SELECT $1::budget.model_call_purpose, $2::text, $3::integer,
       CAST($4::text AS numeric)
WHERE (SELECT coalesce(sum(coalesce(settled_cost_usd, reserved_cost_usd)), 0) FROM budget.model_calls)
      <= CAST($5::text AS numeric)
RETURNING id
`

type ReserveModelCallParams struct {
	Purpose         BudgetModelCallPurpose `json:"purpose"`
	Model           string                 `json:"model"`
	PromptVersion   *int32                 `json:"prompt_version"`
	ReservedCostUsd string                 `json:"reserved_cost_usd"`
	LimitUsd        string                 `json:"limit_usd"`
}

// Model call log in the budget schema (phase 2 LLD section 5). Costs cross
// as decimal strings; the comparison with the limit happens here, in numeric.
// No index: the running total sums at most about 10^4 rows (data model
// section 9).
// Reserves the call's worst-case price only while the running total is at
// most the limit, in one statement, so the total and the new row come from
// the same snapshot. No row means the budget is used up.
func (q *Queries) ReserveModelCall(ctx context.Context, arg ReserveModelCallParams) (int64, error) {
	row := q.db.QueryRow(ctx, reserveModelCall,
		arg.Purpose,
		arg.Model,
		arg.PromptVersion,
		arg.ReservedCostUsd,
		arg.LimitUsd,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const runningTotalUSD = `-- name: RunningTotalUSD :one
SELECT (coalesce(sum(coalesce(settled_cost_usd, reserved_cost_usd)), 0))::text AS total_usd
FROM budget.model_calls
`

func (q *Queries) RunningTotalUSD(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, runningTotalUSD)
	var total_usd string
	err := row.Scan(&total_usd)
	return total_usd, err
}

const settleModelCall = `-- name: SettleModelCall :execrows
UPDATE budget.model_calls
SET outcome = 'settled', input_tokens = $1::integer, output_tokens = $2::integer,
    settled_cost_usd = CAST($3::text AS numeric), updated_at = now()
WHERE id = $4 AND outcome = 'reserved'
`

type SettleModelCallParams struct {
	InputTokens    int32  `json:"input_tokens"`
	OutputTokens   int32  `json:"output_tokens"`
	SettledCostUsd string `json:"settled_cost_usd"`
	ID             int64  `json:"id"`
}

func (q *Queries) SettleModelCall(ctx context.Context, arg SettleModelCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleModelCall,
		arg.InputTokens,
		arg.OutputTokens,
		arg.SettledCostUsd,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
