// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type UserRole string

const (
	UserRoleBrandAdmin    UserRole = "brand_admin"
	UserRoleOutletManager UserRole = "outlet_manager"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

// One location of the brand. Serves US-01-001, US-01-002, US-01-005, US-01-006, US-01-007, US-00-001.
type Outlet struct {
	// Surrogate key; reviews and managers reference it.
	ID int64 `json:"id"`
	// Outlet name as the admin typed it; the CSV outlet column must match it, ignoring case.
	Name string `json:"name"`
	// When the outlet was added.
	CreatedAt time.Time `json:"created_at"`
	// Last change to this row.
	UpdatedAt time.Time `json:"updated_at"`
}

// An account from the users file; one brand admin and outlet managers. Serves US-00-001, US-00-003, US-01-001, US-01-009, US-02-006.
type User struct {
	// Surrogate key; the only identity the JWT carries (ADR-0007).
	ID int64 `json:"id"`
	// Sign-in name and the digest recipient address. [personal data]
	Email string `json:"email"`
	// Name shown in the top bar and beside a reply the manager marked replied. [personal data]
	Name string `json:"name"`
	// brand_admin or outlet_manager, re-read on every request (ADR-0007).
	Role UserRole `json:"role"`
	// The one outlet an outlet manager may see and act on; null for the brand admin.
	OutletID *int64 `json:"outlet_id"`
	// bcrypt hash from the users file; never the password.
	PasswordHash string `json:"password_hash"`
	// Set when the account left the users file; sign-in is refused, the row stays so replies keep their manager.
	RemovedAt *time.Time `json:"removed_at"`
	// When the account was first loaded.
	CreatedAt time.Time `json:"created_at"`
	// Last change from the users file.
	UpdatedAt time.Time `json:"updated_at"`
}
