// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outlets.sql

package store

import (
	"context"
	"time"
)

const createOutlet = `-- name: CreateOutlet :one
INSERT INTO outlets (name)
VALUES ($1)
ON CONFLICT (lower(name)) DO NOTHING
RETURNING id, name, created_at
`

type CreateOutletRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

// No row when the name exists ignoring case; uq_outlets_name_lower.
func (q *Queries) CreateOutlet(ctx context.Context, name string) (CreateOutletRow, error) {
	row := q.db.QueryRow(ctx, createOutlet, name)
	var i CreateOutletRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getOutletByName = `-- name: GetOutletByName :one
SELECT id, name, created_at
FROM outlets
WHERE lower(name) = lower($1::text)
`

type GetOutletByNameRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

// The existing outlet after a CreateOutlet conflict; uq_outlets_name_lower.
func (q *Queries) GetOutletByName(ctx context.Context, name string) (GetOutletByNameRow, error) {
	row := q.db.QueryRow(ctx, getOutletByName, name)
	var i GetOutletByNameRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listActiveManagers = `-- name: ListActiveManagers :many
SELECT id, name, outlet_id
FROM users
WHERE outlet_id = ANY ($1::bigint[])
  AND role = 'outlet_manager'
  AND removed_at IS NULL
ORDER BY lower(name), id
`

type ListActiveManagersRow struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	OutletID *int64 `json:"outlet_id"`
}

// The active managers of the listed outlets; idx_users_outlet_id.
func (q *Queries) ListActiveManagers(ctx context.Context, outletIds []int64) ([]ListActiveManagersRow, error) {
	rows, err := q.db.Query(ctx, listActiveManagers, outletIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveManagersRow
	for rows.Next() {
		var i ListActiveManagersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.OutletID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutletNames = `-- name: ListOutletNames :many
SELECT id, name
FROM outlets
ORDER BY id
`

type ListOutletNamesRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// Every outlet, for matching the CSV outlet column by name ignoring case.
// Known full scan, at most about 25 rows.
func (q *Queries) ListOutletNames(ctx context.Context) ([]ListOutletNamesRow, error) {
	rows, err := q.db.Query(ctx, listOutletNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutletNamesRow
	for rows.Next() {
		var i ListOutletNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutlets = `-- name: ListOutlets :many

SELECT o.id, o.name, o.created_at,
       (SELECT count(*) FROM reviews r WHERE r.outlet_id = o.id)::integer AS review_count,
       (SELECT count(*) FROM reviews r
        WHERE r.outlet_id = o.id
          AND NOT EXISTS (SELECT 1 FROM review_tags t WHERE t.review_id = r.id))::integer AS untagged_count
FROM outlets o
WHERE ($1::boolean OR o.id = $2::bigint)
ORDER BY lower(o.name), o.id
`

type ListOutletsParams struct {
	AllOutlets bool  `json:"all_outlets"`
	OutletID   int64 `json:"outlet_id"`
}

type ListOutletsRow struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	CreatedAt     time.Time `json:"created_at"`
	ReviewCount   int32     `json:"review_count"`
	UntaggedCount int32     `json:"untagged_count"`
}

// Outlets: the list and the add form (phase 1 server LLD, section 5).
// The caller's outlets: every outlet for the brand admin (all_outlets), else
// the manager's one outlet. The scope is an explicit boolean plus an id, never
// "null means all" (tenet 3). Known full scan, at most about 25 rows.
// The two counts read reviews by outlet (idx_reviews_outlet_id_review_date)
// and the untagged anti-join (review_tags_pkey).
func (q *Queries) ListOutlets(ctx context.Context, arg ListOutletsParams) ([]ListOutletsRow, error) {
	rows, err := q.db.Query(ctx, listOutlets, arg.AllOutlets, arg.OutletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutletsRow
	for rows.Next() {
		var i ListOutletsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ReviewCount,
			&i.UntaggedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
