// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replies.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDraft = `-- name: ClaimDraft :one
INSERT INTO replies (review_id)
SELECT r.id FROM reviews r WHERE r.id = $1 AND r.outlet_id = $2
ON CONFLICT (review_id) DO NOTHING
RETURNING updated_at
`

type ClaimDraftParams struct {
	ReviewID int64 `json:"review_id"`
	OutletID int64 `json:"outlet_id"`
}

// No row when a reply exists or the review is not in the manager's outlet.
func (q *Queries) ClaimDraft(ctx context.Context, arg ClaimDraftParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, claimDraft, arg.ReviewID, arg.OutletID)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const getReply = `-- name: GetReply :one
SELECT rp.status::text AS status, rp.draft_text, rp.prompt_version, rp.reply_text, rp.replied_at, rp.updated_at,
       u.id AS replied_by_id, u.name AS replied_by_name
FROM replies rp
LEFT JOIN users u ON u.id = rp.replied_by
WHERE rp.review_id = $1
`

type GetReplyRow struct {
	Status        string     `json:"status"`
	DraftText     *string    `json:"draft_text"`
	PromptVersion *int32     `json:"prompt_version"`
	ReplyText     *string    `json:"reply_text"`
	RepliedAt     *time.Time `json:"replied_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	RepliedByID   *int64     `json:"replied_by_id"`
	RepliedByName *string    `json:"replied_by_name"`
}

func (q *Queries) GetReply(ctx context.Context, reviewID int64) (GetReplyRow, error) {
	row := q.db.QueryRow(ctx, getReply, reviewID)
	var i GetReplyRow
	err := row.Scan(
		&i.Status,
		&i.DraftText,
		&i.PromptVersion,
		&i.ReplyText,
		&i.RepliedAt,
		&i.UpdatedAt,
		&i.RepliedByID,
		&i.RepliedByName,
	)
	return i, err
}

const getReviewDetail = `-- name: GetReviewDetail :one

SELECT r.id, r.outlet_id, o.name AS outlet_name, r.source, r.review_date, r.rating, r.review_text, r.reviewer_name,
       (t.review_id IS NOT NULL)::boolean AS tagged,
       coalesce(t.themes, '{}')::text[] AS themes,
       coalesce(t.sentiment::text, '')::text AS sentiment,
       coalesce(t.is_urgent, false) AS is_urgent,
       coalesce(t.urgent_reasons, '{}')::text[] AS urgent_reasons,
       coalesce(t.prompt_version, 0)::integer AS tag_prompt_version
FROM reviews r
JOIN outlets o ON o.id = r.outlet_id
LEFT JOIN review_tags t ON t.review_id = r.id
WHERE r.id = $1
  AND ($2::boolean OR r.outlet_id = $3::bigint)
`

type GetReviewDetailParams struct {
	ID            int64 `json:"id"`
	AllOutlets    bool  `json:"all_outlets"`
	ScopeOutletID int64 `json:"scope_outlet_id"`
}

type GetReviewDetailRow struct {
	ID               int64       `json:"id"`
	OutletID         int64       `json:"outlet_id"`
	OutletName       string      `json:"outlet_name"`
	Source           string      `json:"source"`
	ReviewDate       pgtype.Date `json:"review_date"`
	Rating           int16       `json:"rating"`
	ReviewText       string      `json:"review_text"`
	ReviewerName     string      `json:"reviewer_name"`
	Tagged           bool        `json:"tagged"`
	Themes           []string    `json:"themes"`
	Sentiment        string      `json:"sentiment"`
	IsUrgent         bool        `json:"is_urgent"`
	UrgentReasons    []string    `json:"urgent_reasons"`
	TagPromptVersion int32       `json:"tag_prompt_version"`
}

// Replies: the claim, the draft, edits and marking replied (phase 5 LLD
// section 3). Every statement reaches the reply through its review and the
// caller's outlet (tenet 3); replies_pkey and reviews_pkey.
func (q *Queries) GetReviewDetail(ctx context.Context, arg GetReviewDetailParams) (GetReviewDetailRow, error) {
	row := q.db.QueryRow(ctx, getReviewDetail, arg.ID, arg.AllOutlets, arg.ScopeOutletID)
	var i GetReviewDetailRow
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.OutletName,
		&i.Source,
		&i.ReviewDate,
		&i.Rating,
		&i.ReviewText,
		&i.ReviewerName,
		&i.Tagged,
		&i.Themes,
		&i.Sentiment,
		&i.IsUrgent,
		&i.UrgentReasons,
		&i.TagPromptVersion,
	)
	return i, err
}

const insertHandReply = `-- name: InsertHandReply :execrows
INSERT INTO replies (review_id, status, reply_text)
SELECT r.id, 'draft', $1::text FROM reviews r
WHERE r.id = $2 AND r.outlet_id = $3
ON CONFLICT (review_id) DO NOTHING
`

type InsertHandReplyParams struct {
	Text     string `json:"text"`
	ReviewID int64  `json:"review_id"`
	OutletID int64  `json:"outlet_id"`
}

// A reply written by hand when there is none (drafting unavailable).
func (q *Queries) InsertHandReply(ctx context.Context, arg InsertHandReplyParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertHandReply, arg.Text, arg.ReviewID, arg.OutletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const landDraft = `-- name: LandDraft :execrows
UPDATE replies
SET status = 'draft', draft_text = $1::text, reply_text = $1::text,
    prompt_version = $2, updated_at = now()
WHERE review_id = $3 AND status = 'drafting' AND updated_at = $4
`

type LandDraftParams struct {
	Text          string    `json:"text"`
	PromptVersion *int32    `json:"prompt_version"`
	ReviewID      int64     `json:"review_id"`
	Claimed       time.Time `json:"claimed"`
}

func (q *Queries) LandDraft(ctx context.Context, arg LandDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, landDraft,
		arg.Text,
		arg.PromptVersion,
		arg.ReviewID,
		arg.Claimed,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markReplied = `-- name: MarkReplied :execrows
UPDATE replies rp
SET status = 'replied', reply_text = $1::text, replied_by = $2, replied_at = now(), updated_at = now()
FROM reviews r
WHERE rp.review_id = $3 AND r.id = rp.review_id AND r.outlet_id = $4
  AND rp.status = 'draft' AND rp.updated_at = $5
`

type MarkRepliedParams struct {
	Text     string    `json:"text"`
	UserID   *int64    `json:"user_id"`
	ReviewID int64     `json:"review_id"`
	OutletID int64     `json:"outlet_id"`
	Seen     time.Time `json:"seen"`
}

func (q *Queries) MarkReplied(ctx context.Context, arg MarkRepliedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markReplied,
		arg.Text,
		arg.UserID,
		arg.ReviewID,
		arg.OutletID,
		arg.Seen,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseClaim = `-- name: ReleaseClaim :exec
DELETE FROM replies
WHERE review_id = $1 AND status = 'drafting' AND updated_at = $2
`

type ReleaseClaimParams struct {
	ReviewID int64     `json:"review_id"`
	Claimed  time.Time `json:"claimed"`
}

func (q *Queries) ReleaseClaim(ctx context.Context, arg ReleaseClaimParams) error {
	_, err := q.db.Exec(ctx, releaseClaim, arg.ReviewID, arg.Claimed)
	return err
}

const saveReplyText = `-- name: SaveReplyText :execrows
UPDATE replies rp SET reply_text = $1::text, updated_at = now()
FROM reviews r
WHERE rp.review_id = $2 AND r.id = rp.review_id AND r.outlet_id = $3
  AND rp.status = 'draft' AND rp.updated_at = $4
`

type SaveReplyTextParams struct {
	Text     string    `json:"text"`
	ReviewID int64     `json:"review_id"`
	OutletID int64     `json:"outlet_id"`
	Seen     time.Time `json:"seen"`
}

func (q *Queries) SaveReplyText(ctx context.Context, arg SaveReplyTextParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveReplyText,
		arg.Text,
		arg.ReviewID,
		arg.OutletID,
		arg.Seen,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeOverClaim = `-- name: TakeOverClaim :one
UPDATE replies SET updated_at = now()
WHERE review_id = $1 AND status = 'drafting' AND updated_at < now() - interval '60 seconds'
RETURNING updated_at
`

// A drafting claim older than 60 seconds belongs to a request that died.
func (q *Queries) TakeOverClaim(ctx context.Context, reviewID int64) (time.Time, error) {
	row := q.db.QueryRow(ctx, takeOverClaim, reviewID)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
