// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReviews = `-- name: CountReviews :one
SELECT count(*)::integer
FROM reviews r
LEFT JOIN review_tags t ON t.review_id = r.id
WHERE ($1::boolean OR r.outlet_id = $2::bigint)
  AND ($3::bigint IS NULL OR r.outlet_id = $3::bigint)
  AND ($4::text IS NULL OR r.review_text ILIKE $4::text ESCAPE '\' OR r.reviewer_name ILIKE $4::text ESCAPE '\')
  AND ($5::text IS NULL OR $5::text = ANY (t.themes))
  AND ($6::text IS NULL OR t.sentiment::text = $6::text)
  AND ($7::boolean IS NULL OR t.is_urgent = $7::boolean)
  AND ($8::date IS NULL OR r.review_date >= $8::date)
  AND ($9::date IS NULL OR r.review_date <= $9::date)
`

type CountReviewsParams struct {
	AllOutlets    bool        `json:"all_outlets"`
	ScopeOutletID int64       `json:"scope_outlet_id"`
	OutletID      *int64      `json:"outlet_id"`
	Q             *string     `json:"q"`
	Theme         *string     `json:"theme"`
	Sentiment     *string     `json:"sentiment"`
	IsUrgent      *bool       `json:"is_urgent"`
	DateFrom      pgtype.Date `json:"date_from"`
	DateTo        pgtype.Date `json:"date_to"`
}

func (q *Queries) CountReviews(ctx context.Context, arg CountReviewsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countReviews,
		arg.AllOutlets,
		arg.ScopeOutletID,
		arg.OutletID,
		arg.Q,
		arg.Theme,
		arg.Sentiment,
		arg.IsUrgent,
		arg.DateFrom,
		arg.DateTo,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listReviews = `-- name: ListReviews :many

SELECT r.id, r.outlet_id, o.name AS outlet_name, r.source, r.review_date, r.rating, r.review_text, r.reviewer_name,
       (t.review_id IS NOT NULL)::boolean AS tagged,
       coalesce(t.themes, '{}')::text[] AS themes,
       coalesce(t.sentiment::text, '')::text AS sentiment,
       coalesce(t.is_urgent, false) AS is_urgent,
       coalesce(t.urgent_reasons, '{}')::text[] AS urgent_reasons,
       coalesce(t.prompt_version, 0)::integer AS prompt_version
FROM reviews r
JOIN outlets o ON o.id = r.outlet_id
LEFT JOIN review_tags t ON t.review_id = r.id
WHERE ($1::boolean OR r.outlet_id = $2::bigint)
  AND ($3::bigint IS NULL OR r.outlet_id = $3::bigint)
  AND ($4::text IS NULL OR r.review_text ILIKE $4::text ESCAPE '\' OR r.reviewer_name ILIKE $4::text ESCAPE '\')
  AND ($5::text IS NULL OR $5::text = ANY (t.themes))
  AND ($6::text IS NULL OR t.sentiment::text = $6::text)
  AND ($7::boolean IS NULL OR t.is_urgent = $7::boolean)
  AND ($8::date IS NULL OR r.review_date >= $8::date)
  AND ($9::date IS NULL OR r.review_date <= $9::date)
  AND ($10::date IS NULL OR (r.review_date, r.id) < ($10::date, $11::bigint))
ORDER BY r.review_date DESC, r.id DESC
LIMIT $12
`

type ListReviewsParams struct {
	AllOutlets    bool        `json:"all_outlets"`
	ScopeOutletID int64       `json:"scope_outlet_id"`
	OutletID      *int64      `json:"outlet_id"`
	Q             *string     `json:"q"`
	Theme         *string     `json:"theme"`
	Sentiment     *string     `json:"sentiment"`
	IsUrgent      *bool       `json:"is_urgent"`
	DateFrom      pgtype.Date `json:"date_from"`
	DateTo        pgtype.Date `json:"date_to"`
	AfterDate     pgtype.Date `json:"after_date"`
	AfterID       *int64      `json:"after_id"`
	RowLimit      int32       `json:"row_limit"`
}

type ListReviewsRow struct {
	ID            int64       `json:"id"`
	OutletID      int64       `json:"outlet_id"`
	OutletName    string      `json:"outlet_name"`
	Source        string      `json:"source"`
	ReviewDate    pgtype.Date `json:"review_date"`
	Rating        int16       `json:"rating"`
	ReviewText    string      `json:"review_text"`
	ReviewerName  string      `json:"reviewer_name"`
	Tagged        bool        `json:"tagged"`
	Themes        []string    `json:"themes"`
	Sentiment     string      `json:"sentiment"`
	IsUrgent      bool        `json:"is_urgent"`
	UrgentReasons []string    `json:"urgent_reasons"`
	PromptVersion int32       `json:"prompt_version"`
}

// Reviews: the searchable list (phase 4 LLD section 5). Every statement is
// scoped by all_outlets OR outlet_id (tenet 3). Optional filters are null
// when absent. Known full scan for the brand admin at about 10^4 rows.
func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]ListReviewsRow, error) {
	rows, err := q.db.Query(ctx, listReviews,
		arg.AllOutlets,
		arg.ScopeOutletID,
		arg.OutletID,
		arg.Q,
		arg.Theme,
		arg.Sentiment,
		arg.IsUrgent,
		arg.DateFrom,
		arg.DateTo,
		arg.AfterDate,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsRow
	for rows.Next() {
		var i ListReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.OutletID,
			&i.OutletName,
			&i.Source,
			&i.ReviewDate,
			&i.Rating,
			&i.ReviewText,
			&i.ReviewerName,
			&i.Tagged,
			&i.Themes,
			&i.Sentiment,
			&i.IsUrgent,
			&i.UrgentReasons,
			&i.PromptVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
