// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSeedReviews = `-- name: InsertSeedReviews :execrows
INSERT INTO reviews (outlet_id, source, review_date, rating, review_text, reviewer_name)
SELECT o.v, s.v, d.v, r.v, t.v, n.v
FROM unnest($1::bigint[]) WITH ORDINALITY AS o (v, i)
JOIN unnest($2::text[]) WITH ORDINALITY AS s (v, i) USING (i)
JOIN unnest($3::date[]) WITH ORDINALITY AS d (v, i) USING (i)
JOIN unnest($4::smallint[]) WITH ORDINALITY AS r (v, i) USING (i)
JOIN unnest($5::text[]) WITH ORDINALITY AS t (v, i) USING (i)
JOIN unnest($6::text[]) WITH ORDINALITY AS n (v, i) USING (i)
ORDER BY i
`

type InsertSeedReviewsParams struct {
	OutletIds     []int64       `json:"outlet_ids"`
	Sources       []string      `json:"sources"`
	ReviewDates   []pgtype.Date `json:"review_dates"`
	Ratings       []int16       `json:"ratings"`
	ReviewTexts   []string      `json:"review_texts"`
	ReviewerNames []string      `json:"reviewer_names"`
}

func (q *Queries) InsertSeedReviews(ctx context.Context, arg InsertSeedReviewsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSeedReviews,
		arg.OutletIds,
		arg.Sources,
		arg.ReviewDates,
		arg.Ratings,
		arg.ReviewTexts,
		arg.ReviewerNames,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetDomainTables = `-- name: ResetDomainTables :exec

TRUNCATE digests, replies, review_tags, import_rejections, reviews, imports, users, outlets
`

// Seed: the demo reset and its reviews (HLD flow D, data model section 5).
// The seed holds the tagging lock while it runs; the budget schema is never
// touched.
func (q *Queries) ResetDomainTables(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetDomainTables)
	return err
}

const restartReviewIDs = `-- name: RestartReviewIDs :exec
ALTER TABLE reviews ALTER COLUMN id RESTART WITH 1
`

// Review ids, batch order and texts must match the recordings on every seed.
func (q *Queries) RestartReviewIDs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restartReviewIDs)
	return err
}
