// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tagging.sql

package store

import (
	"context"
)

const insertReviewTag = `-- name: InsertReviewTag :execrows
INSERT INTO review_tags (review_id, themes, sentiment, is_urgent, urgent_reasons, prompt_version)
VALUES ($1, $2::text[], $3::sentiment, $4,
        $5::text[], $6)
ON CONFLICT (review_id) DO NOTHING
`

type InsertReviewTagParams struct {
	ReviewID      int64     `json:"review_id"`
	Themes        []string  `json:"themes"`
	Sentiment     Sentiment `json:"sentiment"`
	IsUrgent      bool      `json:"is_urgent"`
	UrgentReasons []string  `json:"urgent_reasons"`
	PromptVersion int32     `json:"prompt_version"`
}

// One result per review, never replaced (REQ-011, tenet 4); review_tags_pkey.
func (q *Queries) InsertReviewTag(ctx context.Context, arg InsertReviewTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertReviewTag,
		arg.ReviewID,
		arg.Themes,
		arg.Sentiment,
		arg.IsUrgent,
		arg.UrgentReasons,
		arg.PromptVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockTagging = `-- name: LockTagging :exec
SELECT pg_advisory_lock($1::bigint)
`

// Blocks until this session holds the tagging lock (ADR-0006). The caller
// runs it on a connection of its own and closes that connection to release.
func (q *Queries) LockTagging(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, lockTagging, key)
	return err
}

const reviewTexts = `-- name: ReviewTexts :many
SELECT id, review_text
FROM reviews
WHERE id = ANY ($1::bigint[])
ORDER BY id
`

type ReviewTextsRow struct {
	ID         int64  `json:"id"`
	ReviewText string `json:"review_text"`
}

// The texts of one batch; reviews_pkey.
func (q *Queries) ReviewTexts(ctx context.Context, ids []int64) ([]ReviewTextsRow, error) {
	rows, err := q.db.Query(ctx, reviewTexts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewTextsRow
	for rows.Next() {
		var i ReviewTextsRow
		if err := rows.Scan(&i.ID, &i.ReviewText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const untaggedReviewIDs = `-- name: UntaggedReviewIDs :many

SELECT r.id
FROM reviews r
WHERE r.id > $1::bigint
  AND NOT EXISTS (SELECT 1 FROM review_tags t WHERE t.review_id = r.id)
ORDER BY r.id
`

// Tagging: the worker's snapshot, the texts it sends and the results it
// stores (phase 3 LLD, sections 6 and 7).
// Reviews with no stored result after the given id, in id order: the
// worker's pending work (ADR-0006). reviews_pkey and the review_tags_pkey
// anti-join.
func (q *Queries) UntaggedReviewIDs(ctx context.Context, afterID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, untaggedReviewIDs, afterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
