// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
	"time"
)

const getActiveUserByEmail = `-- name: GetActiveUserByEmail :one

SELECT u.id, u.email, u.name, u.role, u.outlet_id, o.name AS outlet_name, u.password_hash, u.created_at
FROM users u
LEFT JOIN outlets o ON o.id = u.outlet_id
WHERE lower(u.email) = lower($1::text)
  AND u.removed_at IS NULL
`

type GetActiveUserByEmailRow struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	Role         UserRole  `json:"role"`
	OutletID     *int64    `json:"outlet_id"`
	OutletName   *string   `json:"outlet_name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

// Users: sign-in lookups and the users file sync (phase 1 server LLD, section 5).
// Emails and outlet names are compared with lower() inside SQL, so callers pass
// them as written.
// Sign-in by email ignoring case; uq_users_email_lower.
func (q *Queries) GetActiveUserByEmail(ctx context.Context, email string) (GetActiveUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getActiveUserByEmail, email)
	var i GetActiveUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.OutletID,
		&i.OutletName,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveUserByID = `-- name: GetActiveUserByID :one
SELECT u.id, u.email, u.name, u.role, u.outlet_id, o.name AS outlet_name, u.password_hash, u.created_at
FROM users u
LEFT JOIN outlets o ON o.id = u.outlet_id
WHERE u.id = $1
  AND u.removed_at IS NULL
`

type GetActiveUserByIDRow struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	Role         UserRole  `json:"role"`
	OutletID     *int64    `json:"outlet_id"`
	OutletName   *string   `json:"outlet_name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

// The user re-read on every signed-in request (tenet 3); users_pkey.
func (q *Queries) GetActiveUserByID(ctx context.Context, id int64) (GetActiveUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveUserByID, id)
	var i GetActiveUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.OutletID,
		&i.OutletName,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const markUsersRemovedExcept = `-- name: MarkUsersRemovedExcept :execrows
UPDATE users
SET removed_at = now(), updated_at = now()
WHERE removed_at IS NULL
  AND lower(email) <> ALL (SELECT lower(e) FROM unnest($1::text[]) AS e)
`

// Accounts no longer in the file. The list is never empty (the file always
// keeps its one admin): "<> ALL" over an empty list is true for every row.
// Known full scan, about 10 rows.
func (q *Queries) MarkUsersRemovedExcept(ctx context.Context, emails []string) (int64, error) {
	result, err := q.db.Exec(ctx, markUsersRemovedExcept, emails)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveOutletsByName = `-- name: ResolveOutletsByName :many
SELECT id, name
FROM outlets
WHERE lower(name) IN (SELECT lower(n) FROM unnest($1::text[]) AS n)
`

type ResolveOutletsByNameRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// The outlets the users file's managers name; uq_outlets_name_lower.
func (q *Queries) ResolveOutletsByName(ctx context.Context, names []string) ([]ResolveOutletsByNameRow, error) {
	rows, err := q.db.Query(ctx, resolveOutletsByName, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveOutletsByNameRow
	for rows.Next() {
		var i ResolveOutletsByNameRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :execrows
INSERT INTO users (email, name, role, outlet_id, password_hash)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (lower(email)) DO UPDATE
SET email = EXCLUDED.email,
    name = EXCLUDED.name,
    role = EXCLUDED.role,
    outlet_id = EXCLUDED.outlet_id,
    password_hash = EXCLUDED.password_hash,
    removed_at = NULL,
    updated_at = now()
WHERE (users.email, users.name, users.role, users.outlet_id, users.password_hash, users.removed_at)
    IS DISTINCT FROM (EXCLUDED.email, EXCLUDED.name, EXCLUDED.role, EXCLUDED.outlet_id, EXCLUDED.password_hash, NULL::timestamptz)
`

type UpsertUserParams struct {
	Email        string   `json:"email"`
	Name         string   `json:"name"`
	Role         UserRole `json:"role"`
	OutletID     *int64   `json:"outlet_id"`
	PasswordHash string   `json:"password_hash"`
}

// One file entry; changes nothing (0 rows) when every field already matches.
// uq_users_email_lower.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertUser,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.OutletID,
		arg.PasswordHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
